package com.company.cplayer.gui;

import javax.swing.*;
import java.awt.*;

/**
 * Created on 17.02.2017.
 * At 20:10.
 * Today is пятница
 */
public class MainFrame extends JFrame {
    private JPanel rootPanel;
    private JButton fileButton;
    private JButton viewButton;
    private JButton settingsButton;
    private JButton stopButton;
    private JButton pauseButton;
    private JButton playButton;
    private JPanel panel2;
    private JPanel scenePanel;
    private JPanel popupPanel;

    private MainFrame(String title) {
        super(title);
        setContentPane(rootPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
    }

    public MainFrame(String title, int width, int height) {
        this(title);
        setSize(width, height);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setEnabled(false);
        panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        rootPanel.add(panel2, BorderLayout.NORTH);
        fileButton = new JButton();
        fileButton.setText("File");
        panel2.add(fileButton);
        viewButton = new JButton();
        viewButton.setText("View");
        panel2.add(viewButton);
        settingsButton = new JButton();
        settingsButton.setText("Settings");
        panel2.add(settingsButton);
        scenePanel = new JPanel();
        scenePanel.setLayout(new BorderLayout(0, 0));
        rootPanel.add(scenePanel, BorderLayout.CENTER);
        popupPanel = new JPanel();
        popupPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        popupPanel.putClientProperty("html.disable", Boolean.FALSE);
        scenePanel.add(popupPanel, BorderLayout.SOUTH);
        stopButton = new JButton();
        stopButton.setText("Stop");
        popupPanel.add(stopButton);
        pauseButton = new JButton();
        pauseButton.setText("Pause");
        popupPanel.add(pauseButton);
        playButton = new JButton();
        playButton.setText("Play");
        popupPanel.add(playButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
